# Generated by Django 4.0.4 on 2022-04-26 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('roupa', 'Roupa'), ('livros', 'Livros e Cadernos'), ('escrita', 'Material de Escrita'), ('sebentas', 'Apontamentos e Sebentas'), ('casa', 'Casa'), ('outros', 'Outros')], default='outros', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_imagem', models.CharField(default='utilizador.png', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
                ('descricao', models.TextField()),
                ('nome_imagem', models.CharField(default='', max_length=100)),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado')], default='novo', max_length=100)),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibuy.categoria')),
                ('utilizador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('produto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibuy.produto')),
                ('utilizador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
