# Generated by Django 4.0.4 on 2022-04-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibuy', '0003_produto_imagem_produto_nome_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
