# Generated by Django 4.0.4 on 2022-04-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibuy', '0004_remove_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome_imagem',
        ),
    ]
