# Generated by Django 4.0.4 on 2022-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibuy', '0006_produto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.IntegerField(default=0),
        ),
    ]
