# Generated by Django 4.0.4 on 2022-05-09 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ibuy', '0009_rename_produto_fk_comentario_produto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizador',
            old_name='nome_imagem',
            new_name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.CharField(default='produto.png', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
