# Generated by Django 4.0.4 on 2022-05-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibuy', '0010_rename_nome_imagem_utilizador_imagem_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='tipo',
            field=models.CharField(default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='imagem',
            field=models.CharField(default='utilizador.svg', max_length=100),
        ),
    ]
