# Generated by Django 4.0.4 on 2022-05-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibuy', '0011_utilizador_credito_utilizador_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='tipo',
        ),
    ]
