# Generated by Django 4.0.4 on 2022-05-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibuy', '0012_remove_utilizador_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='video_embed',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
