# Generated by Django 4.0.4 on 2022-05-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibuy', '0016_produto_timestamp_alter_produto_preco_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AlterField(
            model_name='produto',
            name='condicao',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado')], default='Novo', max_length=100),
        ),
    ]
